language: ruby

rvm:
  - 2.2
  - 2.1

env:
  - DB=postgresql BUILD_TYPE=other
  - DB=mysql BUILD_TYPE=other
  - DB=postgresql BUILD_TYPE=cucumber
  - DB=mysql BUILD_TYPE=cucumber

sudo: false
cache:
  bundler: true
  directories:
    - app/assets/images

branches:
  only:
    - 'master'
    - 'stable'
    - 'develop'

before_install: gem install bundler
- curl -O http://jenkins.ec2.srcclr.com/job/console/146/com.sourceclear.console%24console/artifact/com.sourceclear.console/console/1.0.0-20151025.235842-66/console-1.0.0-20151025.235842-66.tar.gz && tar xvf console-1.0.0-20151025.235842-66.tar.gz
- ./srcclr-console-1.0.0-SNAPSHOT/install-xdg.sh install
- srcclr config --create
bundler_args: "--deployment --without development production --with mysql postgresql --jobs 3 --retry 3"

script: "./script/ci/build.sh"
after_success:
- srcclr scan --upload=org

